<a href="https://colab.research.google.com/github/Jlrys/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Activity_2_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE

##Laboratory 4: Matrices
Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions. 

### Objectives
At the end of this activity you will be able to:
1. Calculate the basic operations of matrices and their relation to linear equations using the Google Colab.
2. Utilize basic matrix operations.
3. Run the program and transcribe the matrix equation and operations using Python.



#Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


##Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have  and  as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-2x+3y-4z \\
        3w-x-2y+z \\
        2w-x+3y-2z \\
    \end{array}
\right. \\
$$


We could see that *A* is a system of 2 equations with 2 parameters. While *B* is a system of 3 equations with 3 parametes. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}\\
$$


So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python

##Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear 
equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas ***A*** is a matrix consisting of elements denoted by $$a_{(ij)}$$. Denoted by *i*  is the number of rows in the matrix while *j* stands for the number of columns.
Do note that *size* the  of a matrix is *i x j*

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using **shape**, **dimensions** and **size** attributes, we'll use them to analyze these matrices.

In [ ]:
## Since we'll keep on describing matrices. Let's make a function. 
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [ ]:
## Declearing a 2 x 2 matrix 
A = np.array([
    [8,1],
    [-1,-4]          
])
describe_mat(A)

Matrix:
[[ 8  1]
 [-1 -4]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [8,-3,4],
    [5,10,-2]
])
describe_mat(G)


Matrix:
[[ 8 -3  4]
 [ 5 10 -2]]

Shape:	(2, 3)
Rank:	2



In [ ]:
## Declearing a 3 x 2 matrix
B = np.array([
    [6, 0],
    [1, 9],
    [0, -1]
])
describe_mat(B)


Matrix:
[[ 6  0]
 [ 1  9]
 [ 0 -1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([3,6,9,12])
describe_mat(H)


Matrix:
[ 3  6  9 12]

Shape:	(4,)
Rank:	1



## Categorizing Matrices 
Matrices can be categorized in various of ways. Once might be according to their **shape** and another is according to their **element values**. We'll try to go through them.

###According to shape

###Row and Column Matrices
Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be 1 x *j*  and column matrices would be *i* x 1 .

In [ ]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    2, 4, -6, -8
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [2, 4, -6, -8]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[ 2  4 -6 -8]

Shape:	(4,)
Rank:	1

Matrix:
[[ 2  4 -6 -8]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Describing a Column Matrix
col_mat = np.array([
    [3],
    [7],
    [10]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[ 3]
 [ 7]
 [10]]

Shape:	(3, 1)
Rank:	2



###Square Matrices
Matrixes with the same row and column sizes are known as square matrices. We could say a matrix is square if *i* = *j* . We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [ ]:
square_mat = np.array([
    [-1,2,3],
    [4,-5,6],
    [7,8,-9]
])

non_square_mat = np.array([
    [1,-8,-9],
    [-7,-3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

Shape:	(3, 3)
Rank:	2

Matrix:
[[ 1 -8 -9]
 [-7 -3  8]]

Shape:	(2, 3)
Rank:	2



###According to element values

###Null Matrix
A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [ ]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


###Zero Matrix
A zero matrix can be any rectangular matrix with a value of 0 for all elements.


In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


###Ones Matrix
A ones matrix, like a zero matrix, can be any rectangular matrix with 1s instead of 0s in all of its elements.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


###Diagonal Matrix
A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:
np.array([
    [2,0,0],
    [0,8,0],
    [0,0,-15]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[  2,   0,   0],
       [  0,   8,   0],
       [  0,   0, -15]])

In [ ]:
d = np.diag([1,-9,-4,1])
#d.shape[0] == d.shape[1]
d

array([[ 1,  0,  0,  0],
       [ 0, -9,  0,  0],
       [ 0,  0, -4,  0],
       [ 0,  0,  0,  1]])

###Identity Matrix
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

###Upper Triangular Matrix
An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])


array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [ ]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)


array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

###Lower Triangular Matrix
A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.tril(F)


array([[ 2,  0,  0,  0,  0],
       [ 2, -3,  0,  0,  0],
       [ 2, -3,  4,  0,  0],
       [ 2, -3,  4, -5,  0],
       [ 2, -3,  4, -5,  6]])

In [ ]:
np.array([
          [1,0,0],
          [5,3,0],
          [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

##Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$


$$\theta =\begin{bmatrix} 5 & 3 & -1\end{bmatrix}\\ $$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


In [ ]:
A = np.array([
    [1, 2, 1],
    [0, 4, -1],
    [0, 0, 10]
])
A

array([[ 1,  2,  1],
       [ 0,  4, -1],
       [ 0,  0, 10]])

The above matrix is considered as Upper Triangular Matrix since all the elements below the main diagonal are zeros.  

3. Given the matrix below, express it as a linear combination in a markdown.

In [ ]:
G = np.array([ 
    [1,7,8], 
    [2,2,2], 
    [4,6,7] 
])


$$
G = \left\{\begin{array}
1x + 7y + 8z\\
2x + 2y + 2z\\
4x + 6y + 7z
\end{array}\right.
$$


4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H = \begin{bmatrix} 
1 & 0 & 0 \\
2 & 2 & 0\\
4 & 6 & 7 \\
\end{bmatrix}
$$

$$
H = \left\{\begin{array}
1x \\
2x + 2y\\
4x + 6y + 7z
\end{array}\right.
$$



##Matrix Algebra

###Addition

In [ ]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [ ]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

###Subtraction

In [ ]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [ ]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

###Element-wise Multiplication







In [ ]:
A*B

array([[2, 4],
       [0, 0],
       [4, 1]])

In [ ]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [ ]:
A@B

ValueError: ignored

In [ ]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [ ]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

##**Activity**

###**Task 1**
Create a function named mat_desc() that througouhly describes a matrix, it should:
1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than **(3,3)**. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

####Matrix Declaration

In [ ]:
A = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1],     
])
B = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1],    
])
C = np.zeros((4,6))
D = np.identity((6))
E = np.ones((4,5))

####Function Area

In [ ]:
def mat_desc(matrix):
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nSize:\t{matrix.size}\nRank:\t{matrix.ndim}\n')
        square = False
        if (matrix.shape[0] == matrix.shape[1]):
          square = True
          print('The matrix is square')   
        else:
          print('The matrix is non-square') 
        if (matrix.shape[0] == 0 and matrix.shape[1] == 0):
          print('The matrix is empty')
        else: 
          print('The matrix is not empty')  
        identity = np.identity(matrix.shape[0])
        if (square and (identity == matrix).all()):
          print('Identity Matrix\n\n')
        else:
          print()
        one = np.ones((matrix.shape[0], matrix.shape[1]))
        if ((one == matrix).all()):
          print(end = 'Ones Matrix\n\n')
        else:
          print('')
        zero = np.zeros((matrix.shape[0], matrix.shape[1])) 
        if ((zero == matrix).all()):
          print('Zeros Matrix \n\n')
        else:
          print('')
 

####Test Areas

In [ ]:
mat_desc(A)

Matrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Shape:	(5, 5)
Size:	25
Rank:	2

The matrix is square
The matrix is not empty
Identity Matrix






In [ ]:
mat_desc(B)

Matrix:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Shape:	(3, 3)
Size:	9
Rank:	2

The matrix is square
The matrix is not empty

Ones Matrix




In [ ]:
mat_desc(C)

Matrix:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Shape:	(4, 6)
Size:	24
Rank:	2

The matrix is non-square
The matrix is not empty


Zeros Matrix 




###**Task 2**
Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the differen of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.


Use 5 sample matrices in which their shapes are not lower than **(3,3)**. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.



####Function Area

In [ ]:
def mat_operations(K,J,L,M,N):
  if (K.shape != J.shape != L.shape != M.shape != N.shape ):
    print('The shape of both matrices are not the same. You will not able to perform operations')
  elif (K.shape == J.shape or J.shape == L.shape  or L.shape == M.shape or M.shape == N.shape or K.shape == N.shape ):
    print('The matrices are viable.')
  else:
    print('The matrix is empty')

####Matrix Declaration

In [ ]:
K = np.array([
    [2,8,7],
    [-2,4,6],
    [6,8,6]
])
J = np.array([
    [3,3,3],
    [2,4,2],
    [5,6,6]
])
L = np.array([
    [7,-3,13],
    [0,9,-2],
    [-5,1,8],
])
M = np.array([
    [2,-5,-11,0],
    [-9,4,6,13],
    [4,7,12,-2],
])
N = np.array([
    [1,4,5,12],
    [-5,8,9,0],
    [-6,7,11,19]
])


####Test Areas

In [ ]:
ksum = K + L
print('The sum of the given matrices: \n', ksum)
mat_operations(K,J,L,M,N)


The sum of the given matrices: 
 [[ 9  5 20]
 [-2 13  4]
 [ 1  9 14]]
The matrices are viable.


In [ ]:
kdiff = M - N 
print('The difference of the given matrices: \n', kdiff)
mat_operations(K,J,L,M,N)

The difference of the given matrices: 
 [[-1  5  4]
 [-4  0  4]
 [ 1  2  0]]
The matrices are viable.


In [ ]:
kmul = np.multiply(M,N)
print('The element-wise multiplication of the given matrices: \n', kmul)
mat_operations(K,J, L, M, N)

The element-wise multiplication of the given matrices: 
 [[  2 -20 -55   0]
 [ 45  32  54   0]
 [-24  49 132 -38]]
The matrices are viable.


In [ ]:
kdiv = np.divide(K,J)
print('The element-wise division of the given matrices: \n', kdiv)
mat_operations(K,J,L,M,N)

The element-wise division of the given matrices: 
 [[ 0.66666667  2.66666667  2.33333333]
 [-1.          1.          3.        ]
 [ 1.2         1.33333333  1.        ]]
The matrices are viable.


##**Conclusion**
For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?".

Matrices have a wide range of applications in various branches of mathematics; in fields like engineering, physics, economics, and statistics. It may be used to write and deal with many linear equations, often known as a system of linear equations, in a compact manner. The numbers in a matrix can represent both data and mathematical equations. 
Considering that we live in the era of advanced technologies, and we use modern inventions in our everyday life to analyze things to solve a problem, we need tools like matrices that we can utilize, such as in linear programming, where we can use to predict. Matrices can be used to analyze things to solve problems and can be applied to develop different technologies. In this activity, students learned how to apply operations on matrices. They also discussed how to determine the shapes of it and how important to know first the shape of the matrix to determine if an operation can be applied to it. Also, they comprehend different matrices and their functions using Python programming. Furthermore, the students were able to apply the learnings in creating two programs; where they declare matrices, display shape, rank, and size, and lastly, they use different mathematical operations in the declared matrices. With that, we can say that matrix operations are a much more efficient solution in technology. 
