<a href="https://colab.research.google.com/github/Jlrys/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Activity_3_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 6 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.


###Objectives
At the end of this activity you will be able to:
1.	Familiarize the basic matrix operations.
2.	Solve intermediate equation using the operations.
3.	Use matrix algebra to solve engineering problems.


##Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

##Transposition
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} -8 & 4 & 7\\2 & 3 &-5 \\ 4 & -1 & 0\end{bmatrix} $$


$$A^T = \begin{bmatrix} -8 & 2 & 4\\4 & 3 &-1 \\ 7 & -5 & 0\end{bmatrix} $$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
A = np.array([
    [5,8,6],
    [0,-8, -4],
    [9,3,0],
])
A

array([[ 5,  8,  6],
       [ 0, -8, -4],
       [ 9,  3,  0]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 5,  0,  9],
       [ 8, -8,  3],
       [ 6, -4,  0]])

In [ ]:
AT2 = A.T
AT2

array([[ 5,  0,  9],
       [ 8, -8,  3],
       [ 6, -4,  0]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [2,-5,8,10], 
    [3,6,-1,-2],
    [-7,4,1,8],
])
B.shape

(3, 4)

In [ ]:
np.transpose(B).shape

(4, 3)

In [ ]:
B.T.shape

(4, 3)

##Dot Product / Inner Product
If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$
X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}
$$

"$$X\cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}\end{bmatrix}
$$


So if we assign values to $X$ and $Y$

$$
X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, 
Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}
$$

$$
X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix}
= \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}
$$

This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator. 

In [ ]:
J = np.array ([
    [6,5,8],
    [8,-5,7]
])

C = np.array([
   [1,-2],
   [-8,9],
   [2,4],
])

In [ ]:
np.array_equiv(J,C)

False

In [ ]:
np.dot(J,C)

array([[-18,  65],
       [ 62, -33]])

In [ ]:
J.dot(C)

array([[-18,  65],
       [ 62, -33]])

In [ ]:
J@C

array([[-18,  65],
       [ 62, -33]])

In [ ]:
np.matmul(J,C)

array([[-18,  65],
       [ 62, -33]])

In [ ]:
R = np.array([
    [4,7,4,5], 
    [1,-1,7,-5],
    [8,3,-7,0],
])
S = np.array([
    [1,0,2],
    [1,7,-9],
    [-2,-1,-7],
    [0,1,9],
])

In [ ]:
R@S

array([[  3,  50, -38],
       [-14, -19, -83],
       [ 25,  28,  38]])

In [ ]:
R.dot(S)

array([[  3,  50, -38],
       [-14, -19, -83],
       [ 25,  28,  38]])

In [ ]:
np.matmul(R,S)

array([[  3,  50, -38],
       [-14, -19, -83],
       [ 25,  28,  38]])

In [ ]:
np.dot(R,S)

array([[  3,  50, -38],
       [-14, -19, -83],
       [ 25,  28,  38]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

###Rule 1: The inner dimensions of the two matrices in question must be the same.

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$
A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix},  
B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, 
C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}
$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A\cdot C$, or $B\cdot C$.  

In [ ]:
Y = np.array([
    [-4,-8,-3],
    [9,6,3],
    [1,0,-5],
])
U = np.array([
    [1,0,2,0],
    [-9,-5,-4,-2],
    [0,1,1,-5],
])

M = np.array([
    [1,8,0],
    [-9,7,1],
    [5,7,2],
    [-1,0,1],
])
print(Y.shape)
print(U.shape)
print(M.shape)

(3, 3)
(3, 4)
(4, 3)


In [ ]:
Y@U

array([[ 68,  37,  21,  31],
       [-45, -27,  -3, -27],
       [  1,  -5,  -3,  25]])

In [ ]:
U@M

array([[  11,   22,    4],
       [  18, -135,  -15],
       [   1,   14,   -2]])

In [ ]:
M@U

array([[-71, -40, -30, -16],
       [-72, -34, -45, -19],
       [-58, -33, -16, -24],
       [ -1,   1,  -1,  -5]])

In [ ]:
Y @ M.T

array([[-68, -23, -82,   1],
       [ 57, -36,  93,  -6],
       [  1, -14,  -5,  -6]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A\cdot B$ should have a shape $(a,c)$.

In [ ]:
A @ B.T

array([[20, 23, 19],
       [27, 30, 32],
       [11, 14, 13]])

In [ ]:
X = np.array([
      [1,2,3,0]
])
Y = np.array([
      [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [ ]:
X @ Y.T

array([[13]])

And youcan see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

###Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
1. $A\cdot B \neq B\cdot A$
2. $A\cdot (B\cdot C) = (A\cdot B) \cdot C$
3. $A\cdot(B+C) = A\cdot B + A\cdot C$
4. $(B+C)\cdot A = B\cdot A + C\cdot A$
5. $A\cdot I = A$
6. $A\cdot \emptyset = \emptyset$


I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [ ]:
A = np.array([
      [3,2,1],
      [4,5,1],
      [1,1,1],
])
B = np.array([
      [4,1,6],
      [4,1,9],
      [1,4,8],
])
C = np.array([
      [1,1,0],
      [0,1,1],
      [1,0,1]
])


In [ ]:
np.eye(A)

TypeError: ignored

In [ ]:
A.dot(np.eye(3))

array([[3., 2., 1.],
       [4., 5., 1.],
       [1., 1., 1.]])

In [ ]:
np.array_equal(A@B,B@A)

False

In [ ]:
E = A @ (B @ C)
E

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [ ]:
F = (A @ B) @ C
F

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [ ]:
np.array_equal(E,X)

False

In [ ]:
np.array_equiv(E,F)

True

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A@E

array([[455, 205, 368],
       [862, 385, 691],
       [211,  95, 172]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat, dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

##Determinant
A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be realty used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:

$$
A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}
$$

We can compute for the determinant as:

$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$

So if we have $A$ as:

$$
A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3
$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
X = np.array([
    [4,-7],
    [1,9],
])
np.linalg.det(X)

42.99999999999998

In [ ]:
Z = np.array([
    [0,2,5],
    [8,7,-4],
    [3,-6,-4],
])
np.linalg.det(Z)

-304.9999999999998

##Inverse
The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of \"dividing\" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:

$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$

First, we need to get the determinant of $M$.

$$|M| = (1)(5)-(-3)(7) = 26$$

Next, we need to reform the matrix into the inverse form:

$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$

So that will be:

$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$

For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
O = np.array([
    [8,4],
    [3,5],
])
np.array(O @ np.linalg.inv(O), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
T = np.array([
    [0,2,-7],
    [7,6,-1],
    [-4,6,0]
])
G = np.linalg.inv(T)
G

array([[-0.01321586,  0.09251101, -0.08810573],
       [-0.00881057,  0.06167401,  0.10792952],
       [-0.14537445,  0.01762115,  0.030837  ]])

In [ ]:
T@G

array([[ 1.00000000e+00,  1.38777878e-17, -1.73472348e-17],
       [ 0.00000000e+00,  1.00000000e+00,  1.56125113e-16],
       [ 0.00000000e+00,  6.93889390e-17,  1.00000000e+00]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:

$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
        [1.0, 1.0, 0.5],
        [0.7, 0.7, 0.9],
        [0.3, 0.3, 1.0]
])
weights = np.array([
        [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

##Activity
###Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
J = np.array([
    [2,-7,0,-5],
    [9,-1,3,-4],
    [6,-8,-7,0],
    [-3,1,-2,9],
])
R = np.array([
    [-7,-4,-6,7],
    [0,-1,3,9],
    [2,3,-1,4],
    [-1,5,-3,0]
])
G = np.array([
    [-1,2,-1,6],
    [-9,3,-5,3],
    [-7,-5,3,2],
    [1,0,2,5]
])

$A\cdot B \neq B\cdot A$

In [ ]:
U = J@R
U

array([[ -9, -26, -18, -49],
       [-53, -46, -48,  66],
       [-56, -37, -53, -58],
       [  8,  50,  -4, -20]])

In [ ]:
L = R@J
L

array([[-107,  108,   16,  114],
       [ -18,  -14,  -42,   85],
       [  13,   -5,    8,   14],
       [  25,   26,   36,  -15]])

In [ ]:
np.array_equal(U,L)

False

$A\cdot (B\cdot C) = (A\cdot B) \cdot C$

In [ ]:
I = J @ (R @ G)
I

array([[ 320,   -6,  -13, -413],
       [ 869,   -4,  271, -222],
       [ 702,   42,  -34, -843],
       [-450,  186, -310,   90]])

In [ ]:
E = (J @ R) @ G
E

array([[ 320,   -6,  -13, -413],
       [ 869,   -4,  271, -222],
       [ 702,   42,  -34, -843],
       [-450,  186, -310,   90]])

In [ ]:
np.array_equal(I,E)

True

$A\cdot(B+C) = A\cdot B + A\cdot C$

In [ ]:
Y = J @ (R + G)
Y

array([[ 47, -43,   5, -83],
       [-78, -46, -51, 103],
       [ 59, -14, -40, -60],
       [ 25,  57,   6,   6]])

In [ ]:
V = J @ R + J @ G
V

array([[ 47, -43,   5, -83],
       [-78, -46, -51, 103],
       [ 59, -14, -40, -60],
       [ 25,  57,   6,   6]])

In [ ]:
np.array_equal(Y,V)

True

$(B+C)\cdot A = B\cdot A + C\cdot A$

In [ ]:
B = (R + G) @ J
B

array([[-115,  127,   17,  165],
       [ -48,   89,   -4,  145],
       [ -34,   27,  -32,   87],
       [  24,    8,   12,   25]])

In [ ]:
C = R @ J + G @ J
C

array([[-115,  127,   17,  165],
       [ -48,   89,   -4,  145],
       [ -34,   27,  -32,   87],
       [  24,    8,   12,   25]])

In [ ]:
np.array_equal(B,C)

True

$A\cdot I = A$


In [ ]:
S = np.eye(4)
S

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
W = J @ S
W

array([[ 2., -7.,  0., -5.],
       [ 9., -1.,  3., -4.],
       [ 6., -8., -7.,  0.],
       [-3.,  1., -2.,  9.]])

In [ ]:
np.array_equal(W,J)

True

$A\cdot \emptyset = \emptyset$

In [ ]:
Q = np.zeros(J.shape)
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
N = R @ Q
N

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.array_equal(N,Q)

True

## Conclusion
Through the help of NumPy library, we were able to put into an example the given properties of dot product in matrix algebra. In this activity, it can be realized that the order of matrices as they are being multiplied can result to different products since it does not hold commutative property of multiplication. Moreover, just like how we multiply numbers to 1, multiplying matrix to 1 will also return the matrix itself only. In addition, when we multiply a matrix to zero, it will just result to zero matrix also. In the distributive property, it must be noted to still follow the order of the matrices even if we distribute the other matrix so that it will not change the product. Overall, we have appreciated more the special properties of dot product in matrices from planning its flowchart down to implementation of the plan since we can see the logic behind these properties. Nevertheless, it is best understood when you can see the results, which is the reason why we printed each matrix we made for each property aside from printing whether the property is true or not. 